[workspace]
resolver = "2"
# members = ["easytier", "easytier-gui/src-tauri", "easytier-rpc-build", "easytier-web"]
# default-members = ["easytier"]

members = ["easytier", "easytier-rpc-build"]

[profile.dev]
panic = "unwind"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
